mod about;
mod confirmation;
mod contact;
mod faq;
mod home;
mod hotel_details;
mod how_it_works;
mod legal;
mod listings;
mod my_reservations;
mod my_reviews;
mod not_found;
mod reservation_details;
mod reservation_form;
mod retrieve_booking;
mod sign_in;
mod room_details;

pub use about::AboutPage;
pub use confirmation::ConfirmationPage;
pub use contact::ContactPage;
pub use faq::FaqPage;
pub use home::HomePage;
pub use hotel_details::HotelDetailsPage;
pub use how_it_works::HowItWorksPage;
pub use legal::{PrivacyPage, TermsPage};
pub use listings::ListingsPage;
pub use my_reservations::MyReservationsPage;
pub use my_reviews::{MyReviewsPage, StarPicker};
pub use not_found::NotFoundPage;
pub use reservation_details::ReservationDetailsPage;
pub use reservation_form::ReservationFormPage;
pub use retrieve_booking::RetrieveBookingPage;
pub use sign_in::SignInPage;
pub use room_details::RoomDetailsPage;
